name: JavaCIwithMaveninLinux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
	  - name: CacheMavenpackages
		uses: actions/cache@v4
		with:
		  path: ~/.m2
		  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml')}}
		  restore-keys: ${{ runner.os }}-m2-
      - name: Build with Maven
        run: mvn -f my-project-ci/pom.xml clean verify
